theme: databio

site_name: PEPATAC
site_author: Jason Smith
site_url: http://code.databio.org/PEPATAC/
site_logo: img/pepatac_logo_white.svg
repo_url: https://github.com/databio/pepatac/
google_analytics: ['UA-127092878-1', 'code.databio.org/PEPATAC']

markdown_extensions:
  - fontawesome_markdown  # pip install --user fontawesome-markdown
  - pymdownx.details  # pip install --user pymdown-extensions

nav:
  - Getting Started:
    - Introduction: 'README.md'
    - Features: 'features.md'
    - Install and run test example: 'install.md'
    - Extended tutorial: 'tutorial.md'
  - How-to Guides:
    - Running PEPATAC directly: 'run-directly.md'
    - Running on a cluster: 'run-cluster.md'
    - Running in a container: 'run-container.md'
    - Downloading SRA data: 'download.md'
    - Configuring prealignments: 'prealignments.md'
    - Using a custom peak annotation: 'annotation.md'
    - Detailed install guide: 'detailed-install.md'
  - Reference: 
    - Example output file structure: 'browse_output.md'
    - "Example summary: gold project": 'files/examples/gold/summary.html'
    - "Example summary: tutorial project": 'files/examples/tutorial/tutorial_summary.html'
    - Usage: 'usage.md'
    - FAQ: faq.md
    - Glossary: 'glossary.md'
    - Changelog: changelog.md
    - Support: contact.md

plugins:
  - search
  - databio:
      usage_template: "docs/usage_template.md"
      usage_cmds:
        -"$CODEBASE/databio/pepatac/pipelines/pepatac.py --help

navbar:
  right:
  - text: Software & Data
    icon: fa-code fa-lg
    href: http://databio.org/software/
  # - text: Contact us
  #   icon: fa-envelope
  #   href: contact