
# This project config file describes your project. See looper docs for details.
name: test_project # The name that summary files will be prefaced with

metadata:  # relative paths are relative to this config file
  sample_annotation: test_annotation.csv  # sheet listing all samples in the project
  output_dir: "$HOME/atac_out"  # ABSOLUTE PATH to the parent, shared space where project results go
  pipeline_interfaces: "$CODEBASE/pepatac/pipeline_interface.yaml"  # ABSOLUTE PATH to the directory where looper will find the pipeline repository

# in your sample_annotation, columns with these names will be populated as described 
# in the data_sources section below
derived_columns: [read1, read2]  

data_sources:  # This section describes paths to your data
  # specify the ABSOLUTE PATH of input files using variable path expressions
  # These keys then correspond to values in your sample annotation columns.
  # Variables specified using brackets are populated from sample_annotation columns. 
  # Variable syntax: {column_name}. For example, use {sample_name} to populate
  # the file name with the value in the sample_name column for each sample.
  # example_data_source: "/path/to/data/{sample_name}_R1.fastq.gz"
  test_data_R1: "$CODEBASE/pepatac/examples/data/{sample_name}_r1.fastq.gz"
  test_data_R2: "$CODEBASE/pepatac/examples/data/{sample_name}_r2.fastq.gz"

implied_columns:
  organism:
    human:
      genome: hg38
      macs_genome_size: "hs"
      prealignments: "rCRSd"
    mouse:
      genome: mm10
      macs_genome_size: "mm"
      prealignments: "mouse_chrM2x"
